run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: learn

linters:
  disable-all: true
  enable:
    - goveta       # Official Go vet tool
    - errcheck     # Checks for unchecked errors
    - staticcheck  # Go static analysis, huge number of checks
    - unused       # Checks for unused constants, variables, functions and types
    - gosimple     # Linter for Go source code that specializes in simplifying code
    - structcheck  # Finds unused struct fields
    - varcheck     # Finds unused global variables and constants
    - ineffassign  # Detects when assignments to existing variables are not used
    - deadcode     # Finds unused code
    - typecheck    # Like the front-end of a Go compiler, parses and type-checks code
    - gofmt        # Checks if code is gofmted
    - goimports    # Checks missing or unformatted imports
    - bodyclose    # checks whether HTTP response body is closed successfully
    - noctx        # noctx finds sending http request without context.Context
    - gocyclo      # Checks function and method complexities

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
